#%RAML 1.0
title: Customer API
baseUri: http://localhost:8081/api
version: 1.0

securitySchemes:
  basic:
    description: |
      This API supports Basic Authentication.
    type: Basic Authentication


/customer:
  get:
    securedBy: [basic]
    description: to get customer
    headers:
      customerId:
        type: string
        required: true
  put:
    securedBy: [basic]
    description: to update customer
    headers:
      customerId:
        type: string
        required: true
  post:
    securedBy: [basic]  
    description: To post Customer Details
    body:
     application/json:
            example:  |
              {
              "customerId": "4d4de7d6-7f5e-4778-9c70-babba6c25c55",
              "firstName": "Ulrich",
              "lastName": "Nielsen",
              "companyName": "E-ffoc",
              "email": "ulrichN@effoc.com",
              "phone": "+494341927420"
              }
    responses:
      200:
        body:
          application/json:
            example:  |
             {
                "success."
             }